/* WayaX live screens: offline cache. A new version installs in the background and is used on the next app launch. */
const V = '2026.10.05-1535-a95168c880';
const PRE = ["/preview", "/assets/ai/arrow-up.svg", "/assets/ai/bg-glow-v2.svg", "/assets/ai/bg-glow.svg", "/assets/ai/logo.svg", "/assets/ai/nav-binoculars.svg", "/assets/ai/nav-bookmark.svg", "/assets/ai/nav-briefcase.svg", "/assets/ai/nav-chats.svg", "/assets/ai/nav-skills.svg", "/assets/ai/plus.svg", "/assets/common/bell.svg", "/assets/common/menu.svg", "/assets/common/tab-line-active.svg", "/assets/fonts/Inter.ttf", "/assets/fonts/Sora.ttf", "/assets/intro2/logo-gradient.svg", "/assets/intro2/logo-white.svg", "/assets/ob/ambient-glow.svg", "/assets/ob/check.svg", "/assets/ob/chevron-down.svg", "/assets/ob/lock-keyhole.svg", "/assets/ob/pencil.svg", "/assets/ob/shield-check.svg", "/assets/ob/wayax-logo.svg", "/assets/panel/avatar.png", "/assets/panel/chevron-right.svg", "/assets/panel/chevron-up.svg", "/assets/panel/edit.svg", "/assets/panel/ic-faq.svg", "/assets/panel/ic-plans.svg", "/assets/panel/logo-waya.svg", "/assets/panel/more-vertical.svg", "/assets/panel/search.svg", "/assets/panel/settings.svg", "/assets/rs/bg-glow.svg", "/assets/rs/card-bg-gradient.png", "/assets/rs/ic-arrow-down.svg", "/assets/rs/ic-arrow-up-green.svg", "/assets/rs/ic-arrow-up.svg", "/assets/rs/ic-download.svg", "/assets/rs/ic-file-2.svg", "/assets/rs/ic-file.svg", "/assets/rs/ic-headphone.svg", "/assets/rs/ic-icici.svg", "/assets/rs/ic-maximize-1.svg", "/assets/rs/ic-maximize-2.svg", "/assets/rs/ic-maximize-3.svg", "/assets/rs/ic-minimize.svg", "/assets/rs/ic-more.svg", "/assets/rs/ic-time-1.svg", "/assets/rs/ic-time-2.svg", "/assets/rs/ic-time-3.svg", "/assets/rs/ic-time-4.svg", "/assets/rs/ic-video.svg", "/assets/rs/logo-adani.png", "/assets/rs/logo-icici-2.png", "/assets/rs/logo-icici.png", "/assets/rs/logo-mahindra.png", "/assets/rs/logo-ongc.png", "/assets/rs/logo-sbi.png", "/assets/rs/nav-past.svg", "/assets/rs/nav-play.svg", "/assets/rs/nav-sparkles.svg", "/assets/rs/nav-target.svg", "/assets/rs/nav-trending.svg", "/assets/rs/pagination-sector.svg", "/assets/rs/pagination.svg", "/assets/rs/plot-line-1.svg", "/assets/rs/plot-line-2.svg", "/assets/rs/plot-line-4.svg", "/assets/rs/sector-down-1.svg", "/assets/rs/sector-down-2.svg", "/assets/rs/sector-up-1.svg", "/assets/rs/sector-up-2.svg", "/assets/rs/sector-up-3.svg", "/assets/rs/sector-up-4.svg", "/assets/rs/thumb-1.png", "/assets/rs/thumb-2.png", "/assets/rs/thumb-3.png", "/assets/splash/liquid-left.svg", "/assets/splash/liquid-mid.svg", "/assets/splash/liquid-right.svg", "/assets/splash/piece-left.svg", "/assets/splash/piece-mid.svg", "/assets/splash/piece-right.svg"];
self.addEventListener('install', e => e.waitUntil(
  caches.open('wx-' + V).then(c => c.addAll(PRE.map(u => new Request(u, { cache: 'reload' }))))));
self.addEventListener('activate', e => e.waitUntil(
  caches.keys().then(ks => Promise.all(ks.filter(k => k.startsWith('wx-') && k !== 'wx-' + V).map(k => caches.delete(k))))
    .then(() => self.clients.claim())));
self.addEventListener('message', e => { if (e.data === 'skip') self.skipWaiting(); });
self.addEventListener('fetch', e => {
  const u = new URL(e.request.url);
  if (e.request.method !== 'GET' || u.origin !== location.origin) return;
  if (u.pathname.startsWith('/updates/') || u.pathname === '/screens.json' || u.pathname === '/' || u.pathname === '/index.html') return;
  e.respondWith(caches.open('wx-' + V).then(c => c.match(e.request, { ignoreSearch: true }).then(hit => hit ||
    fetch(e.request).then(r => { if (r.ok && r.type === 'basic') c.put(e.request, r.clone()); return r; }))));
});
